// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.1
// source: pb/session.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionType int32

const (
	SessionType_ST_NONE SessionType = 0
	SessionType_TCP     SessionType = 1
	SessionType_UDP     SessionType = 2
)

// Enum value maps for SessionType.
var (
	SessionType_name = map[int32]string{
		0: "ST_NONE",
		1: "TCP",
		2: "UDP",
	}
	SessionType_value = map[string]int32{
		"ST_NONE": 0,
		"TCP":     1,
		"UDP":     2,
	}
)

func (x SessionType) Enum() *SessionType {
	p := new(SessionType)
	*p = x
	return p
}

func (x SessionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_session_proto_enumTypes[0].Descriptor()
}

func (SessionType) Type() protoreflect.EnumType {
	return &file_pb_session_proto_enumTypes[0]
}

func (x SessionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionType.Descriptor instead.
func (SessionType) EnumDescriptor() ([]byte, []int) {
	return file_pb_session_proto_rawDescGZIP(), []int{0}
}

type HeaderType int32

const (
	HeaderType_HT_NONE HeaderType = 0
	HeaderType_SESSION HeaderType = 1
	HeaderType_USER    HeaderType = 2
)

// Enum value maps for HeaderType.
var (
	HeaderType_name = map[int32]string{
		0: "HT_NONE",
		1: "SESSION",
		2: "USER",
	}
	HeaderType_value = map[string]int32{
		"HT_NONE": 0,
		"SESSION": 1,
		"USER":    2,
	}
)

func (x HeaderType) Enum() *HeaderType {
	p := new(HeaderType)
	*p = x
	return p
}

func (x HeaderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeaderType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_session_proto_enumTypes[1].Descriptor()
}

func (HeaderType) Type() protoreflect.EnumType {
	return &file_pb_session_proto_enumTypes[1]
}

func (x HeaderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeaderType.Descriptor instead.
func (HeaderType) EnumDescriptor() ([]byte, []int) {
	return file_pb_session_proto_rawDescGZIP(), []int{1}
}

type MsgType int32

const (
	MsgType_MT_NONE    MsgType = 0
	MsgType_REMOTEADDR MsgType = 1
	MsgType_SESSIONID  MsgType = 2
	MsgType_CLOSE      MsgType = 255
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:   "MT_NONE",
		1:   "REMOTEADDR",
		2:   "SESSIONID",
		255: "CLOSE",
	}
	MsgType_value = map[string]int32{
		"MT_NONE":    0,
		"REMOTEADDR": 1,
		"SESSIONID":  2,
		"CLOSE":      255,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_session_proto_enumTypes[2].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_pb_session_proto_enumTypes[2]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_pb_session_proto_rawDescGZIP(), []int{2}
}

type SessionMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            []byte      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionType   SessionType `protobuf:"varint,2,opt,name=sessionType,proto3,enum=pb.SessionType" json:"sessionType,omitempty"`
	DialerNknAddr string      `protobuf:"bytes,3,opt,name=dialerNknAddr,proto3" json:"dialerNknAddr,omitempty"`
}

func (x *SessionMetadata) Reset() {
	*x = SessionMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_session_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMetadata) ProtoMessage() {}

func (x *SessionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pb_session_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMetadata.ProtoReflect.Descriptor instead.
func (*SessionMetadata) Descriptor() ([]byte, []int) {
	return file_pb_session_proto_rawDescGZIP(), []int{0}
}

func (x *SessionMetadata) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SessionMetadata) GetSessionType() SessionType {
	if x != nil {
		return x.SessionType
	}
	return SessionType_ST_NONE
}

func (x *SessionMetadata) GetDialerNknAddr() string {
	if x != nil {
		return x.DialerNknAddr
	}
	return ""
}

type SessionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType MsgType `protobuf:"varint,1,opt,name=msgType,proto3,enum=pb.MsgType" json:"msgType,omitempty"`
	Data    []byte  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SessionData) Reset() {
	*x = SessionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_session_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionData) ProtoMessage() {}

func (x *SessionData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_session_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionData.ProtoReflect.Descriptor instead.
func (*SessionData) Descriptor() ([]byte, []int) {
	return file_pb_session_proto_rawDescGZIP(), []int{1}
}

func (x *SessionData) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_MT_NONE
}

func (x *SessionData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pb_session_proto protoreflect.FileDescriptor

var file_pb_session_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x7a, 0x0a, 0x0f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x0b, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x64, 0x69, 0x61, 0x6c, 0x65, 0x72, 0x4e, 0x6b, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x69, 0x61, 0x6c, 0x65, 0x72, 0x4e, 0x6b, 0x6e, 0x41, 0x64,
	0x64, 0x72, 0x22, 0x48, 0x0a, 0x0b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x25, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x2c, 0x0a, 0x0b,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x54, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50, 0x10,
	0x01, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x44, 0x50, 0x10, 0x02, 0x2a, 0x30, 0x0a, 0x0a, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x48, 0x54, 0x5f, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0x02, 0x2a, 0x41, 0x0a, 0x07,
	0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x54, 0x5f, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x45, 0x4d, 0x4f, 0x54, 0x45, 0x41, 0x44,
	0x44, 0x52, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x49,
	0x44, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x05, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0xff, 0x01, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_session_proto_rawDescOnce sync.Once
	file_pb_session_proto_rawDescData = file_pb_session_proto_rawDesc
)

func file_pb_session_proto_rawDescGZIP() []byte {
	file_pb_session_proto_rawDescOnce.Do(func() {
		file_pb_session_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_session_proto_rawDescData)
	})
	return file_pb_session_proto_rawDescData
}

var file_pb_session_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pb_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_session_proto_goTypes = []interface{}{
	(SessionType)(0),        // 0: pb.SessionType
	(HeaderType)(0),         // 1: pb.HeaderType
	(MsgType)(0),            // 2: pb.MsgType
	(*SessionMetadata)(nil), // 3: pb.SessionMetadata
	(*SessionData)(nil),     // 4: pb.SessionData
}
var file_pb_session_proto_depIdxs = []int32{
	0, // 0: pb.SessionMetadata.sessionType:type_name -> pb.SessionType
	2, // 1: pb.SessionData.msgType:type_name -> pb.MsgType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_session_proto_init() }
func file_pb_session_proto_init() {
	if File_pb_session_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_session_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_session_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_session_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_session_proto_goTypes,
		DependencyIndexes: file_pb_session_proto_depIdxs,
		EnumInfos:         file_pb_session_proto_enumTypes,
		MessageInfos:      file_pb_session_proto_msgTypes,
	}.Build()
	File_pb_session_proto = out.File
	file_pb_session_proto_rawDesc = nil
	file_pb_session_proto_goTypes = nil
	file_pb_session_proto_depIdxs = nil
}
